name: Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Install Gitleaks
      - name: Install Gitleaks
        run: |
          wget -q -O /tmp/gitleaks.tar.gz https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz
          tar -xzvf /tmp/gitleaks.tar.gz -C /tmp/
          sudo mv /tmp/gitleaks-linux-amd64/gitleaks /usr/local/bin/

      # Step 3: Run Gitleaks
      - name: Run Gitleaks
        run: gitleaks --path=./

      # Step 4: Install Trivy
      - name: Install Trivy
        run: |
          wget -q -O /tmp/trivy.tar.gz https://github.com/aquasecurity/trivy/releases/latest/download/trivy_linux_amd64.tar.gz
          tar -xzvf /tmp/trivy.tar.gz -C /tmp/
          sudo mv /tmp/trivy /usr/local/bin/

      # Step 5: Run Trivy for file system scanning
      - name: Run Trivy for File System
        run: trivy filesystem --exit-code 1 --severity HIGH,CRITICAL ./ || true
